# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d530b5b77f3c92ffb6f7e93ea6b308aa"
application_url = "https://dista-app-gavyamart.onrender.com"
embedded = true
name = "Dista App - Gavyamart"
handle = "dista-app-gavyamart"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_checkouts,read_customers,read_orders,read_payment_customizations,read_products,read_translations,read_validations,write_checkouts,write_payment_customizations,write_products,write_validations"

[auth]
redirect_urls = [
  "https://dista-app-gavyamart.onrender.com/auth/callback",
  "https://dista-app-gavyamart.onrender.com/auth/shopify/callback",
  "https://dista-app-gavyamart.onrender.com/api/auth/callback"
]

[app_proxy]
url = "https://dista-app-gavyamart.onrender.com"
subpath = "rvpp"
prefix = "a"

[pos]
embedded = false

[build]
include_config_on_deploy = true
